### PR TITLE
💻 Fix font issues on Windows

### LINKED ISSUE #202: Fix font issues on Windows
Some fonts are not being displayed in our custom font face on Windows.

Example: ● character
image

### PR DESCRIPTION
**Pull request by evtyz**
# Purpose
Closes #202.

# Approach
- Explicitly import `Inter` font in `globals.css`
- Conditionally display larger ⬤ character on Windows

# Screenshots
### Before
image

### After 
image

### CODE REVIEW

File: client/components/resource-details/Reviews.tsx [hunk 1]
```diff
@@ -146,7 +146,8 @@ const Rating = styled(
         <RatingLabel>{capitalizeFirstLetter(label)}</RatingLabel>
         <ReactStars
           count={5}
-          char={'●'}
```
Comment (xujustinj) [inline client/components/resource-details/Reviews.tsx:149]: I'm pretty sure there's no shortage of circle-looking Unicode characters. Have we tried using a different one? e.g. what if we use the large circle on all platforms?

**Review by xujustinj — APPROVED** [review]
changes lgtm but I wonder if there's a different solution altogether

File: client/components/resource-details/Reviews.tsx (hunk 1 above)
Comment (evtyz) [reply client/components/resource-details/Reviews.tsx:149]: The large circle looks ridiculously large on Mac. Maybe too large on other platforms too.

From what I can tell, there are only two circle characters, "small black circle" and "large black circle", which can be recoloured. I might be wrong though. 

There is a "medium black circle" but it's hardcoded to be black and the colour can't be changed.
